export const DUMMY_DASHBOARD_VIDEO_LIST = [
  {
    id: 1,
    userId: 5,
    uploaderNickname: "테스트",
    title: "프로젝트 최종 발표 연습1",
    description: "프로젝트 최종 발표를 위한 연습 영상입니다.",
    videoUrl: "~~~",
    thumbnailUrl: "https://placehold.co/600x400/png",
    type: "",
    durationSeconds: 320,
    createdAt: "2026-04-10T12:24:55.623Z",
  },
  {
    id: 2,
    userId: 5,
    uploaderNickname: "테스트",
    title: "면접 자기소개 연습 1차",
    description: "자기소개와 지원동기 답변을 중심으로 연습한 영상입니다.",
    videoUrl: "~~~",
    thumbnailUrl: "https://placehold.co/600x400/png",
    type: "",
    durationSeconds: 185,
    createdAt: "2026-04-11T09:15:22.101Z",
  },
  {
    id: 3,
    userId: 5,
    uploaderNickname: "테스트",
    title: "중간 발표 리허설",
    description: "수업 중간 발표를 대비해 전체 흐름을 점검한 영상입니다.",
    videoUrl: "~~~",
    thumbnailUrl: "https://placehold.co/600x400/png",
    type: "",
    durationSeconds: 274,
    createdAt: "2026-04-12T14:08:37.442Z",
  },
  {
    id: 4,
    userId: 5,
    uploaderNickname: "테스트",
    title: "포트폴리오 발표 연습",
    description: "포트폴리오 소개와 프로젝트 설명 위주로 연습한 영상입니다.",
    videoUrl: "~~~",
    thumbnailUrl: "https://placehold.co/600x400/png",
    type: "",
    durationSeconds: 412,
    createdAt: "2026-04-13T18:42:10.889Z",
  },
];
